# Generated by Django 3.0.6 on 2020-08-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200828_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.IntegerField(blank=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
